FROM nginx

FROM php:7.4-fpm
RUN apt-get update && apt-get install -y --no-install-recommends unzip && \
    docker-php-ext-install pdo pdo_mysql && \
    docker-php-ext-enable pdo_mysql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&\
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/*
